#!/usr/bin/env bash
# pocketsphinx_continuous -adcdev plughw:1,0 -inmic yes -samprate 44100 -nfft 2048 -lm 0916.lm -dict 0916.dic 2>/dev/null
pocketsphinx_continuous -inmic yes -lm 0916.lm -dict 0916.dic 2>/dev/null
